services:
  gui:
    build:
      context: ./src/gui
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - ./gui:/app
    container_name: streamlit-gui
    depends_on:
      redis:
        condition: service_healthy
      test_engine:
        condition: service_healthy
    environment:
      - ROBOT_API_URL=http://test_engine
      - ROBOT_API_PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "docker.arvancloud.ir/redis:latest"
    container_name: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  test_engine:
    build:
      context: ./src/test_engine
    volumes:
      - ./test_engine:/app
    container_name: test-engine
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 3s
      retries: 5