services:
  gui:
    build:
      context: ./gui
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - ./gui:/app
    container_name: streamlit-gui
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - ROBOT_API_URL=http://host.docker.internal
      - ROBOT_API_PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "docker.arvancloud.ir/redis:latest"
    ports:
      - "6379:6379"
    container_name: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
